In [3]:
import pandas as pd
import data_io as io

In [8]:
index_df = pd.read_pickle(io.SAVE_PATH + 'index.pkl')

In [11]:
index_df.head(10)

x0  x1  y0  y1  sample_idx  \
0   3   8   3   8           0   
1   3   8   6  11           0   
2   3   8   9  14           0   
3   3   8  12  17           0   
4   3   8  15  20           0   
5   3   8  18  23           0   
6   3   8  21  26           0   
7   6  11   3   8           0   
8   6  11   6  11           0   
9   6  11   9  14           0   

                                               input  
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, ...  
5  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, ...  
6  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, ...  
7  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...  
8  [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, ...  
9  [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...

In [12]:
index_df.describe()

x0           x1           y0           y1   sample_idx
count  3528.000000  3528.000000  3528.000000  3528.000000  3528.000000
mean     11.541667    16.541667    11.949830    16.949830    49.598073
std       5.998437     5.998437     5.084211     5.084211    28.736546
min       0.000000     5.000000     0.000000     5.000000     0.000000
25%       6.000000    11.000000     9.000000    14.000000    25.000000
50%      12.000000    17.000000    12.000000    17.000000    50.000000
75%      18.000000    23.000000    15.000000    20.000000    75.000000
max      21.000000    26.000000    21.000000    26.000000    99.000000

In [13]:
index_df['x0']

0        3
1        3
2        3
3        3
4        3
        ..
3523    18
3524    18
3525    21
3526    21
3527    21
Name: x0, Length: 3528, dtype: int64

In [16]:
index_df['input']

0       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, ...
                              ...                        
3523    [1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, ...
3524    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3525    [0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, ...
3526    [0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, ...
3527    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: input, Length: 3528, dtype: object

In [17]:
index_df['input'][0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1])

In [18]:
index_df.loc[1]

x0                                                            3
x1                                                            8
y0                                                            6
y1                                                           11
sample_idx                                                    0
input         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: 1, dtype: object

In [21]:
d = {('excite','w1','w0'):[1,2,3], ('excite',0,1):[9,8,7], ('inhibit',0,'x'):[4,5,6]}
df = pd.DataFrame(d)
df

excite    inhibit
      w1  0       0
      w0  1       x
0      1  9       4
1      2  8       5
2      3  7       6

In [22]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [23]:
df.loc[0]

excite   w1  w0    1
         0   1     9
inhibit  0   x     4
Name: 0, dtype: int64

In [24]:
df.loc[0].index

MultiIndex([( 'excite', 'w1', 'w0'),
            ( 'excite',    0,    1),
            ('inhibit',    0,  'x')],
           )

In [32]:
df.loc[0, ('excite', 'w1')]

w0    1
Name: 0, dtype: int64

In [42]:
df = pd.read_pickle(io.SAVE_PATH + 'net_data.pkl')

In [43]:
df.shape

(3529, 425)

In [44]:
df.head()

input                             ...    output                           \
      0  1  2  3  4  5  6  7  8  9  ...         8                        9   
      0  0  0  0  0  0  0  0  0  0  ...         2         3         4    a   
0     0  0  0  0  0  0  0  0  0  0  ...  0.734999  0.263594  0.453872  0.0   
1     0  0  0  0  0  0  0  0  0  0  ...  0.734000  0.262666  0.452720  0.0   
2     0  0  0  0  0  0  0  0  0  0  ...  0.734687  0.262666  0.451345  0.0   
3     0  0  0  0  0  0  0  0  0  0  ...  0.735950  0.261602  0.451716  0.0   
4     0  0  0  0  0  0  0  0  0  0  ...  0.737458  0.261232  0.452835  0.0   

                                                               
                                                               
          p         0         1         2         3         4  
0  0.578518  0.547401  0.300567  0.647727  0.614715  0.800240  
1  0.578518  0.546392  0.299695  0.646864  0.612966  0.799561  
2  0.578518  0.546383  0.300401  0.648345  0.612693  0.798800  
3  0.578518  0.546651  0.300475  0.649014  0.612099  0.799469  
4  0.578518  0.546797  0.300504  0.649315  0.610337  0.800334  

[5 rows x 425 columns]

In [45]:
df.columns

MultiIndex([( 'input', 0,   0),
            ( 'input', 1,   0),
            ( 'input', 2,   0),
            ( 'input', 3,   0),
            ( 'input', 4,   0),
            ( 'input', 5,   0),
            ( 'input', 6,   0),
            ( 'input', 7,   0),
            ( 'input', 8,   0),
            ( 'input', 9,   0),
            ...
            ('output', 8,   2),
            ('output', 8,   3),
            ('output', 8,   4),
            ('output', 9, 'a'),
            ('output', 9, 'p'),
            ('output', 9,   0),
            ('output', 9,   1),
            ('output', 9,   2),
            ('output', 9,   3),
            ('output', 9,   4)],
           length=425)

In [111]:
df.loc[0][( 'hidden', 0)]

a     0.000000
p     0.825799
0     0.963001
1     0.320696
2     0.962197
3     0.755020
4     0.437034
5     0.457407
6     0.002273
7     0.785247
8     0.699705
9     0.750432
10    0.470067
11    0.284622
12    0.578304
13    0.863053
14    0.687286
15    0.617672
16    0.092016
17    0.586650
18    0.091280
19    0.029248
20    0.751994
21    0.214908
22    0.585561
23    0.580600
24    0.425322
Name: 0, dtype: float64

In [116]:
import numpy as np
np.array(df.loc[0][('hidden', 0)])

array([0.        , 0.82579876, 0.96300148, 0.32069604, 0.96219726,
       0.75502026, 0.43703352, 0.45740714, 0.0022731 , 0.7852472 ,
       0.69970542, 0.75043156, 0.4700673 , 0.28462213, 0.57830392,
       0.8630526 , 0.68728577, 0.61767183, 0.09201569, 0.58665042,
       0.0912804 , 0.02924799, 0.75199406, 0.21490805, 0.58556076,
       0.5806002 , 0.4253219 ])

In [118]:
type(df.loc[0][('hidden', 0)])

pandas.core.series.Series

In [128]:
df.loc[0]['hidden']

0  a     0.000000
   p     0.825799
   0     0.963001
   1     0.320696
   2     0.962197
           ...   
9  20    0.136444
   21    0.174175
   22    0.201309
   23    0.841196
   24    0.513157
Name: 0, Length: 270, dtype: float64

In [4]:
df = pd.read_pickle(io.SAVE_PATH + 'net_data.pkl')

In [5]:
df.loc[0]

input      activations    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
hidden     activations    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
           potentials     [0.9381049585303278, 0.6855231441110747, 0.663...
           weights        [[0.4618072235402737, 0.5217700240189488, 0.20...
recurrent  activations                            [0.0, 0.0, 0.0, 0.0, 0.0]
           potentials     [0.852909455517665, 0.9935554400651747, 0.1749...
           weights        [[0.8553634807672716, 0.6325699949629879, 0.61...
output     activations    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
           potentials     [0.9381049585303278, 0.6855231441110747, 0.663...
           weights        [[0.5871541624601688, 0.2157405937631608, 0.28...
Name: 0, dtype: object

In [131]:
df['input']

activations
0     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
1     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
...                                                 ...
3524  [1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, ...
3525  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3526  [0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, ...
3527  [0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, ...
3528  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

[3529 rows x 1 columns]

In [151]:
w = df.loc[1]['hidden', 'weights']
w.shape

(25, 10)

In [12]:
ndf = df.loc[0]['hidden'] - df.loc[1]['hidden']
ndf

activations    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
potentials     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
weights        [[0.0016244797716027382, 0.0007442936205399597...
dtype: object

In [13]:
ndf['weights']

array([[ 1.62447977e-03,  7.44293621e-04,  4.25644486e-04,
         4.28572214e-04,  2.00060143e-05,  2.34513863e-03,
         1.09716808e-03,  7.30620440e-07,  1.93539997e-03,
         3.44378758e-04],
       [ 3.79049535e-03,  4.71673155e-04,  4.43232088e-05,
         2.72614126e-03,  1.11958923e-04,  2.04600807e-04,
         6.11674729e-04,  5.38322379e-08,  3.12833414e-04,
         3.12778326e-04],
       [ 4.19147135e-04,  2.10707177e-03,  4.02042156e-04,
         4.82974728e-04,  4.97538984e-06,  4.60724161e-04,
         1.58092145e-03,  6.47694301e-07,  2.85718707e-03,
         3.64975010e-04],
       [ 1.50212654e-03,  3.23158791e-04,  9.83218179e-04,
         2.68954262e-04,  3.89775764e-05,  1.09446284e-03,
         6.52749431e-04,  1.40134397e-09,  1.66562389e-04,
         3.93181222e-05],
       [ 8.56671768e-04,  2.34728132e-03,  1.53546179e-04,
         1.18456616e-03,  1.55163038e-05,  7.95370908e-04,
         4.06299449e-05,  4.13982434e-07,  2.69544972e-03,
         6.

In [16]:
df.loc[1]['hidden','weights']

array([[0.46018274, 0.52102573, 0.20956943, 0.66310383, 0.66306344,
        0.93634707, 0.49415425, 0.80764812, 0.28491234, 0.39621311],
       [0.6550431 , 0.57903776, 0.73494292, 0.74078813, 0.87620134,
        0.15188769, 0.67878116, 0.0623377 , 0.09927675, 0.39550167],
       [0.88978756, 0.83216951, 0.86937491, 0.70160043, 0.04441987,
        0.20614148, 0.54064536, 0.70290158, 0.46570117, 0.91794916],
       [0.31687128, 0.69281094, 0.48533408, 0.14631781, 0.49515395,
        0.99347185, 0.57802039, 0.00182122, 0.63339322, 0.05031696],
       [0.8673797 , 0.91059068, 0.44414626, 0.25577988, 0.2242808 ,
        0.48125644, 0.5748192 , 0.98680818, 0.99079777, 0.7860497 ],
       [0.71854834, 0.52145367, 0.84651699, 0.08718138, 0.54635433,
        0.92155467, 0.91715873, 0.423147  , 0.78762425, 0.88366975],
       [0.28316862, 0.48289441, 0.4388887 , 0.47356434, 0.0372091 ,
        0.66192213, 0.96802163, 0.0280818 , 0.4092526 , 0.96365464],
       [0.07680833, 0.98068028, 0.6896162